#!/usr/bin/env bash
#
# BSD 3-Clause License
#
# Copyright (c) 2025, © Badassops LLC / Luc Suryo
# All rights reserved.
#

CMD=../release/notify-to-teams_Darwin_arm64

echo "Test Service CRITICAL"
/usr/bin/printf "%b" "ServiceHost: myhost.cloud\nServiceOutput: CRITICAL\nServiceName: NTP\nServiceState: please ignore, testing service critical\n" | $CMD

echo "Test Service OK"
/usr/bin/printf "%b" "ServiceHost: myhost.cloud\nServiceOutput: OK\nServiceName: NTP\nServiceState: please ignore, testing service ok\n" | $CMD

echo "Test Direct message"
$CMD -m "please ignore, testing direct message"
